version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
